name: Deploy app to EC2

on:
  workflow_run:
    workflows: ["CI_PACK"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Project Zip
        uses: actions/download-artifact@v4
        with:
          name: euro_dental_build

      - name: Unzip project
        run: |
          unzip euro_dental_build.zip
          ls -a

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     name: id_rsa  # The default name for the SSH key
      #     known_hosts: ${{ secrets.HOST_DNS }} # This ensures the server is trusted

      # - name: Copy app to EC2 instance
      #   run: |
      #     rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/${{ secrets.USERNAME }}/app/EuroDentalAPI/

      # - name: Install dependencies and restart FastAPI service
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
      #       cd /home/${{ secrets.USERNAME }}/app/EuroDentalAPI/
            
      #       # Ensure virtual environment or dependencies
      #       if [ ! -d ".venv" ]; then
      #         python3 -m venv .venv
      #       fi
      #       source .venv/bin/activate
      #       pip install -r requirements.txt
          
      #       echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      #       echo "DB_USER=${{ secrets.DB_USER }}" >> .env
      #       echo "DB_NAME=eurodental" >> .env

            # Restart FastAPI app (assumes Gunicorn or uvicorn setup)
            sudo systemctl restart fastapi  # Modify based on your app service name
          EOF
