name: Deploy app to EC2
'on':
  workflow_run:
    workflows:
      - CI_PACK
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Project Zip
        uses: actions/download-artifact@v4
        with:
          name: euro_dental_build
      - name: Unzip project
        run: |
          unzip euro_dental_build.zip
          ls -a
